### ISSUE TITLE
Anyway to handle serverside rendering?

### ISSUE THREAD

**Issue by halben** [zefoy/ngx-swiper-wrapper#20] opened 2017-03-30 19:19 UTC
Is there anyway to handle the server side rendering for this library?

I'm running into an issue where it breaks my app during a build. The error is:

ReferenceError: window is not defined ... node_modules/angular2-swiper-wrapper/bundles/angular2-swiper-wrapper.umd.js:5445:22

**Comment by halben** [comment] 2017-03-30 20:37
Just thought of a solution, DI swap. =)

**Comment by sconix** [comment] 2017-03-30 21:32
I am not sure if we can make the Swiper play nice, but I am going to try during April since we would need it as well in our project where we use this library. So unless you want to try to make PR then stay tuned I am going to look into this as soon as possible, but since I have my holiday coming up in two days it might be closer to the end of the month.

**Comment by ahmedshabib** [comment] 2017-05-01 12:25
Even I faced same problem, I found a workaround by executing the swiper code only in browser.
https://github.com/simplymovein/angular2-useful-swiper

**Comment by sconix** [comment] 2017-05-02 07:59
I guess that would work for most of the cases, but I am still hoping that there is a better solution. I should have time to look into the server side rendering during this month.

**Comment by alexverdaguer** [comment] 2017-05-23 09:59
Hi @sconix any progress on the server side rendering ?

@ahmedshabib could you explain me how do it ?

Thank you !

**Comment by sconix** [comment] 2017-05-23 13:43
I haven't looked into it yet. He has resolved the issue in his library to only initialize Swiper if in browser, but this of course wont look the same than in browser. So one could as well just ngIf out the Swiper component on server side rendering to have the same effect.

I don't expect to have a simple solution for this so for now the best is just not to render Swiper components when doing server side rendering.

**Comment by sconix** [comment] 2017-08-02 09:14
It seems that there is a pull request for Swiper to be compatible with server side rendering. Hopefully that gets merged at some point since that would the best place to fix this problem.

**Comment by MarkPieszak** [comment] 2017-08-27 18:31
Closed out https://github.com/zefoy/ngx-swiper-wrapper/issues/50 (as its a duplicate), but it would be great to have it basically ignore everything in server renders, and not load up swiper.js at all

**Comment by sconix** [comment] 2017-08-27 19:29
I haven't looked into the server rendering yet so I have no idea whats the real problem is. If its not the importing of Swiper only using it then what prevents you do just have simple ngIf not to use the swiper element on server render. So I don't see a point for adding a hack into the library when it can be very easily handled.

**Comment by darcksday** [comment] 2017-08-31 09:37
How  initializing swiper  only in browser without duplicate code with *ngIf?

**Comment by sconix** [comment] 2017-08-31 10:16
Not sure if I understood your question but you can use ng-template to not duplicate any template code just have one if that places the content either inside swiper element or normal div.

**Comment by stephenlautier** [comment] 2017-09-21 13:18
It doesn't seem that only an `*ngIf` is required in order to work for SSR. Even if I only add the module it will break SSR (without usages) e.g. 

```
SwiperModule.forRoot({
    direction: "horizontal"
})

// I get the following:
ReferenceError: window is not defined
```

It's because it loads the swiper and it gets caused due to it.

So most probably in order to get it work is to only load the `SwiperModule` in app module (browser) only. 
When I do that I run on other issues, such as `swiper`  element not defined, so it requires a polyfill element or disables schema errors. Even if I do all this in my current setup I didn't get it to work yet, because I have `AppBrowserModule`, `AppServerModule` and `AppSharedModule` and my components are registered on the Shared so my components won't be aware of Swiper.
My setup is based on the [.NET Core SPA Template](https://github.com/aspnet/templating/tree/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp/ClientApp).

Would be nice to understand how they got it working e.g.

- Do you load `SwiperModule` in app browser module only?
  - _If yes_ - do you disable schema validation on the server?
  - _If yes_ - do you register your components in the shared or done both in browser/server seperately?
  - _if not_ - how do you load it and it doesnt throw any errors on the server due the issue i mentioned above?
- Do you wrap your usages for swiper

**Comment by MarkPieszak** [comment] 2017-09-23 19:13
@stephenlautier 
Since it's a directive it has to be loaded into the AppModule, you could load a Module only into AppBrowserModule for instance if it was a Service or something.

So having it in AppModule causing a few problems, since of course that means the Server will have it as well. This is the worst case scenario for SSR since it means you have to mock out server implementations (usually just stubbed out), and have webpack -replace- them on the fly, during bundling, of your server bundle.

It depends on how you're using this library, but a client I had worked on, it took these next few steps to get it going.

In your webpack file for the `server` only, add:

```
const NormalModuleReplacementPlugin = require('webpack/lib/NormalModuleReplacementPlugin');

// then in your plugins add... 

plugins: [
    new NormalModuleReplacementPlugin(
      /swiper.js/,
      path.resolve(__dirname, 'src/server-mocks/mock-swiper-js.js')
    ),
    new NormalModuleReplacementPlugin(
      /swiper.directive/,
      path.resolve(__dirname, 'src/server-mocks/mock-ngx-swiper-directive.js')
    )
  ]
```

So you can see I'm replacing them with 2 files here. ^^ 

Those 2 files look like this, put them in a gist:
https://gist.github.com/MarkPieszak/0e7f4174e258a9be22e5561d92a7a443

You'll also find in there a really quick mock Directive that we're including in the AppServerModule in declarations that has the basic functionality of the SwiperDirective for the server.

It's a crazy process, but fortunately it's easier with Angular than it is with other frameworks.

---

**Ideally** we should be distributing a **`server`** version of the ngx-swiper-wrapper repo here that's basically just the stubbed out version with nothing in it, almost an abstraction of the real implementation.

**Comment by stephenlautier** [comment] 2017-09-25 09:25
@MarkPieszak thanks for your detailed reply. I can give this a shot. 
Unfortunately its still a bit complicated with universal when it depends on 3rd party libraries such as swiper.js. Hopefully, they do something about it to simplify, but at least its already listed in their roadmap.

> Make it easier to support other 3rd part libraries like jQuery/d3 that aren't Universal aware

Thanks again.

**Comment by sconix** [comment] 2017-10-16 13:18
I am releasing new version most likely tomorrow which uses the latest Swiper 4.x which should have server side rendering support.

**Comment by picosam** [comment] 2017-10-16 14:29
@sconix Lovely, thank you! Will you need to update the docs to reflect usage changes?

**Comment by sconix** [comment] 2017-10-16 15:45
Lets see I will release the new version tomorrow with updated docs etc. But I will make the release with @next tag. So the 4.x versions I leave as they are to use Swiper 3 and the upcoming 5.0.0 release will use Swiper 4 + fully support Angular 4/5.

It seems that the new Swiper has lots of cool stuff like build in mutation observer to reduce the need for manual update calls etc.

I will comment here once the release is out and close this issue.

**Comment by dalvarezr** [comment] 2017-10-22 02:19
W8ting for updates...

**Comment by sconix** [comment] 2017-10-22 06:57
I will release new version in few days, been waiting for the Swiper 4.x api docs to update so I can make sure everything is supported. They are now out so I should be able to get this release out in day or two as soon as I have time to test everything. The Swiper 4.x is said to have server side rendering support, but there was still one issue with that and don't know if its already fixed, anyway I believe that there will be 4.x release that will work with server side rendering.

**Comment by Jeka-Endorphin** [comment] 2017-10-24 08:53
After release still "ERROR ReferenceError: Swiper is not defined"

**Comment by sconix** [comment] 2017-10-24 09:00
There has not been new release yet.

**Comment by sconix** [comment] 2017-10-25 10:07
I just made a new pre-release 5.0.0-5 which uses Swiper 4.x. I haven't tested if the server side rendering issues have been fixed, but if some found then I suggest to report them in the Swiper issues so those will get fixed. At least the server side rendering support for mentioned in the 4.x changelog.

**Comment by pivalig** [comment] 2017-10-30 08:57
with latest version i got this :
swiper_1.default is not a constructor

from swiper.directive.js:100
   this.zone.runOutsideAngular(function () {
            _this.swiper = new swiper_1.default(_this.elementRef.nativeElement, options);
        });

trying to render swiper only in browser

**Comment by sconix** [comment] 2017-10-30 12:00
Do you have correct version of Swiper? Since it is working for us, we are using the latest in our production app.

**Comment by itanev** [comment] 2017-11-01 09:29
Hi,

After updating to 4.6.6 I am still getting the "window is not defined" error on server side pre-rendering. Am I missing something? Is there something different in the initialization of the new version that I should do?

**Comment by itanev** [comment] 2017-11-01 12:23
Hi,

After building the rc the 'window is not defined' error disappeared, but now I am getting 'document is not defined'.

The error seems to be caused by an event called 'onwheel'. Unfortunately, I am unable to understand much more about this because I am looking at a minified file.

Is this a bug or I have build the library in a wrong way? I have used the steps in your Readme:

npm install
npm run build
npm run inline

**Comment by sconix** [comment] 2017-11-01 12:29
That sounds like a bug / feature in Swiper, but have you tried disabling the mousewheel component for server side? I don't know if those extra components should be server friendly, most likely not since they don't make sense to be used on server side. If that won't help then you could report the issue to Swiper repository.

**Comment by itanev** [comment] 2017-11-02 09:49
hmm... it seems like that swiper have fixed the document issue in [this commit].(https://github.com/nolimits4web/Swiper/commit/e28632b53866fba15a3b34208ecee257506078b7)

I updated the swiper version to 4.0.3 in the package.json of your package and it seems to fix the issue. Of course, there are new errors now, but I think they are related to my implementation. :)

**Comment by sconix** [comment] 2017-11-02 10:17
Thanks for the info, I will update the dependencies for next release.

**Closed** 2017-12-22 11:57 UTC
