### ISSUE TITLE
Slides per view causes missing slides

### ISSUE THREAD

**Issue by zurie** [zefoy/ngx-swiper-wrapper#24] opened 2017-05-07 16:27 UTC
Issue:
When navigating backwards (left) with slides per view enabled by default, every slide.length + 2 of slides is blank, so you have 3 slides, every 5th slide is blank backwards. 

I am trying to find the exact place where things mess up but I can help reproduce the steps required to cause this issue.

If you use your default demo with looping enabled and you start with one slide in view and toggle "slides per view" to 3 everything works as expected.

if you look at the console.log you see

Swiper index: 3
Swiper index: 2
Swiper index: 1
Swiper index: 4
Swiper index: 3
Swiper index: 2
Swiper index: 1

the index decreases with every left navigation of your slides.

But if you change your config inside the typescript so that it loads with 3 slides per view by default you will see this in console.log

Swiper index: 3
Swiper index: 2
Swiper index: 5
Swiper index: 0
Swiper index: 3
Swiper index: 2
Swiper index: 5
Swiper index: 0

In a real world example I started with slides per view and noticed that incrementing my slides backwards would result in a blank / missing slide every full cycle.  If i set the slides to 1 and use a button or init function to change it to 3 per view I never see missing slides.  There is something thats messing up on the initial initialization of this component.

**Comment by sconix** [comment] 2017-05-08 05:30
Have you tried calling update(true) after the slidesPerView change? The "automatic" update mechanism does not use the true parameter to be bit more lightweight, but some changes do need it for the styles to update correctly. So try calling the update(true) manually after the config change, if that helps I could add the true parameter when ever the slidesPerView config changes to the "automatic" update mechanism.

**Comment by zurie** [comment] 2017-05-08 12:17
how would I go about calling the update parameter?   Are you saying mySwiper.update(updateTranslate);	

im not 100% sure how I need to reference my swiper so that I can call the Update.

**Comment by sconix** [comment] 2017-05-08 20:47
Ah sorry I misunderstood your report, I though you are changing the sliderPerView dynamically. I will try tomorrow with the example if I can reproduce what you are reporting. But I must say that we have been using the slidesPerView in our app without any problems, so maybe there is just something in the example app.

**Comment by zurie** [comment] 2017-05-08 21:58
I did some more testing on my own and I think this may be why its difficult to notice it.

    slidesPerView: 3 or 4 or any number higher than 1,
    centeredSlides: true,
    loop: true,


When you don't use "centeredSlides" the left most slide is always aligned with the container, so you will never see the missing slide because its to the left of the container and outside the overflow of the container div.  When you use "centeredSlides" and "loop" swiper makes a copy of your last slide in the loop and puts it on the opposite side of the loop so that when you get to last slide you see your first slide sitting next to it on the tail end and can continuously loop forward.  When you go forward / right in your loop you don't have the problem or its difficult to see the problem because your cards are sliding off the screen as the problem happens,  but when you go reverse you can easily see the issue, look at the index and go reverse from 0 to the last slide, so 0 to 5 to 0 , etc.  go left and right from 0 and you should see the slides vanish.

Not sure if this is a swiper issue or the component issue because it does require some setup to get swiper in the situation that you'd notice it.    

I have a demo you can see. you can goto 
[http://dev.zadesigns.com/about](url) 
open the console log and scroll the page down to the blue section with the swiper (middle) you can use the arrow keys to navigate forward and backwards.  Go forwards till 5, then start going backwards and forwards and you can see when it goes from 0 to 5 it kills the slides on the left.  if you stop when the slides are invisible and grab with the cursor the slides show up, so its some sort of bug, but i can get it to happen with the included demo using loop, center slides, and slidesperview.

thanks! for your help

**Comment by zurie** [comment] 2017-05-08 22:04
wonder if this is the issue
https://github.com/nolimits4web/Swiper/issues/2030

**Comment by sconix** [comment] 2017-05-09 06:58
I think it might be, at least it most likely because the loop option. We use both slidesPerView and centeredSlides in our project and have no issues with them.

**Comment by linpekka** [comment] 2017-10-04 07:32
I seem to trigger this with loop and slidesPerView only, no need for centeredSlides. I also get stuck in a never ending loop of showing exactly the same 3 slides if I get loop, slidesPerView:3 and slidesPerGroup:3.

**Comment by sconix** [comment] 2017-10-04 08:04
Does the abovr Swiper bug match what you are experiencing?

**Comment by linpekka** [comment] 2017-10-04 08:52
I was a bit of in my first comment, sorry for any confusion, turns out I have 4 slides in the carousel, got misinterpreted the duplicates and whatnot created by the initialisation, and if I just use slidesPerView and loop I get all 4 slides. 
I do miss one slide, and get stuck in a loop of 3 slides, if I use slidesPerGroup, and seems to require slidesPerGroup to be number of slides -1. 
So different issue, sorry, perhaps related. I am on the latest stable also, not the latest beta.

**Comment by sconix** [comment] 2017-10-16 15:53
Tomorrow I will release new version which uses Swiper 4.x and I hope this issue will be fully resolved with that.

**Closed by sconix** 2017-10-16 15:53 UTC
