### ISSUE TITLE
Issue with overlay pagination control in example

### ISSUE THREAD

**Issue by hassanasad** [zefoy/ngx-swiper-wrapper#115] opened 2018-01-20 09:12 UTC
I had slight issues with the swiper overlay pagination controls in my app. I just checked them on example ( https://zefoy.github.io/ngx-swiper-wrapper/ ) and it also has some issues. They do not work most of the time. You have to click slightly towards the left of each dot to make it work. Can you please look into this. Seems to have appeared during one of the updates

**Comment by sconix** [comment] 2018-01-20 09:38
Thanks, I will fix it for next release. For now you can either use directive or provide your own custom bullet renderer.

**Comment by sconix** [comment] 2018-01-21 20:25
Actually with closer look it seems that this is Swiper bug. I will try to find the root cause and make a bug report next week. For now it seems that with the component it works if you do not set the clickable: true for the pagination config (component has its own click handling).

**Comment by sconix** [comment] 2018-01-21 21:01
I was wrong it was a small styling bug in the component. This is fixed in 5.3.0 which is out really soon.

**Closed by sconix** 2018-01-21 21:01 UTC
